### ISSUE TITLE
Release firewood on weekly chron job

### ISSUE THREAD

**Issue by exdx** [ava-labs/firewood#52]
It's possible to trigger an automatic tag push to main via a chron job. This would simplify the release of week patches -- it would automatically push the next z+1 release on Friday 5pm EST for example. 

Example code:
```
on:
  push:
    branches: [master, dev]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master, dev]
  schedule:
    - cron: "44 11 * * 4"
```
